### ISSUE TITLE
The localpart of an emailaddress must be treated as case sensitive

### ISSUE THREAD

**Issue by Sjaaky** [Qowaiv/Qowaiv#103]
[Section 2.4 of RFC 5321](https://www.rfc-editor.org/rfc/rfc5321.html#section-2.4):

> The local-part of a mailbox MUST BE treated as case sensitive.

https://github.com/Qowaiv/Qowaiv/blob/21d2d46be0418b14c12a18e1dad47af84eb3a5ff/src/Qowaiv/EmailParser.cs#L97

**Comment by Corniel** [comment]
Fixed.
