### ISSUE TITLE
Why are the structs not readonly?

### ISSUE THREAD

**Issue by sonnemaf** [Qowaiv/Qowaiv#241]
Hi,

Is there a reason why the structs are not readonly? It seems that all fields are readonly so they could be marked readonly. This would avoid defensive copies when used in `readonly fields`, `ref readonly locals` and `in` parameters. The primitives of .NET 3+ are (almost) all readonly. I think these should be too.

```cs
readonly struct Percentage {
    ...
}
```

**Comment by Corniel** [comment]
The reason is in the support of `IXmlSerialization`. As Microsoft could work around it for its own primitives (in relation to XML serialization) but we normal mortals can not. Unless, I've missed something.

**Comment by sonnemaf** [comment]
The primitives (int, double, decimal, string) of Microsoft don't implement this interface. Why do you? Maybe you should drop it and make the structs readonly.

At least make all (pure) methods readonly. This will avoid the defensive copies too.

**Comment by Corniel** [comment]
@sonnemaf The don't have to, as they are all special cases in the XML Serializer; they can be found here: [https://source.dot.net/#System.Private.Xml/System/Xml/Serialization/XmlSerializer.cs](https://source.dot.net/#System.Private.Xml/System/Xml/Serialization/XmlSerializer.cs,b9604a3aca6f8489).

I don't understand how I could make [Pure] methods read-only? What do you mean with that?

**Comment by sonnemaf** [comment]
@Corniel I reviewed it and it looks ok. 

I really would have preferred real readonly structs. They show there intent. Noda time had the same issue, see [IMPLEMENTING IXMLSERIALIZABLE IN READONLY STRUCTS](https://codeblog.jonskeet.uk/2018/03/02/implementing-ixmlserializable-in-readonly-structs/)

Maybe it is time for an [C# 8.0 and C# 9.0 training](https://reflectionit.nl/training/csharp/csharp-8-9) 😊

**Comment by sonnemaf** [comment]
Hi @Corniel 

I think I found a solution for the `IXmlSerialization` interface. You can make the structs readonly when you use the `Unsafe.AsRef()` method in the `ReadXml()` method. Have a look at this example using a simple Point struct. The project doesn't need the Unsafe compiler flag. I 'stole' the solution from [NodaTime](https://github.com/nodatime/nodatime/blob/main/src/NodaTime/Interval.cs).

```cs
using System;
using System.IO;
using System.Runtime.CompilerServices;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;

var point = new Point(1, 2);
Console.WriteLine(point.ToString());
Console.WriteLine(point.Dist);

// Serialize
XmlSerializer serializer = new XmlSerializer(typeof(Point));
using (var sw = new StringWriter()) {
    serializer.Serialize(sw, point);
    sw.Flush();
    Console.WriteLine(sw.ToString());
}

// Deserialize
using (var sr = new StringReader(@"<Point>3:4</Point>")) {
    point = (Point)serializer.Deserialize(sr);
}

Console.WriteLine(point.ToString());
Console.WriteLine(point.Dist);

public readonly struct Point : IXmlSerializable {

    public readonly int X; // { get; set; }
    public readonly int Y; // { get; set; }

    public Point(int x, int y) {
        X = x;
        Y = y;
    }

    public double Dist => Math.Sqrt((X * X) + (Y * Y));

    public override string ToString() => $"{X}:{Y}";

    public XmlSchema GetSchema() => null!;

    public void ReadXml(XmlReader reader) {
        var span = reader.ReadElementContentAsString().AsSpan();
        var index = span.IndexOf(':');
        int x = int.Parse(span.Slice(0, index));
        int y = int.Parse(span.Slice(index + 1));
        Unsafe.AsRef(this) = new Point(x, y);
    }

    public void WriteXml(XmlWriter writer) {
        writer.WriteString(this.ToString());
    }
}
```

**Comment by Corniel** [comment]
That is indeed elegant. In practice, the generated code should look like this:
``` C#
void IXmlSerializable.ReadXml(XmlReader reader)
{
    Guard.NotNull(reader, nameof(reader));
    var xml = reader.ReadElementString();
    Unsafe.AsRef(this) = Parse(xml, CultureInfo.InvariantCulture);
}
```

The only downside I see, is the dependency on `System.Runtime.CompilerServices.Unsafe`, where Qowaiv previously did not require any external dependency besides `netstandard2.0`.  I have to give this a thought.

**Comment by sonnemaf** [comment]
When you do decide to implement this you can remove all the readonly members from #243.

NodaTime did it so I think you should do this too. It seems to be common practice.

**Comment by Corniel** [comment]
@sonnemaf Common practice is a strong term for something that has not been broadly adopted. I like the clarity of it. That's beyond doubt. Any dependency you introduce with a package as this, can be seen as reason not to do it. So that is worth a consideration.
