### ISSUE TITLE
LCOV file can not be found

### ISSUE THREAD

**Issue by Corniel** [Qowaiv/Qowaiv#284]
Due to the changes in the the build scripts, now the LCOV (coverage) file can not be found anymore: https://github.com/Qowaiv/Qowaiv/actions/runs/3523295263

**Comment by Sjaaky** [comment]
These lines are in the logfile:

  Generating report '/home/runner/work/Qowaiv/Qowaiv/specs/Qowaiv.Specs/coverage.netcoreapp3.1.json'
  Generating report '/home/runner/work/Qowaiv/Qowaiv/specs/Qowaiv.Specs/coverage.net5.0.json'
  Generating report '/home/runner/work/Qowaiv/Qowaiv/specs/Qowaiv.Specs/coverage.net6.0.json'
  Generating report '/home/runner/work/Qowaiv/Qowaiv/specs/Qowaiv.Specs/coverage.net7.0.json'

While the logfile of last successful run contains:

  Generating report '/home/runner/work/Qowaiv/Qowaiv/specs/Qowaiv.Specs/coverage.info'
