### ISSUE TITLE
Parser not supporting 3 more formats

### ISSUE THREAD

**Issue by salmarko** [Qowaiv/Qowaiv#68]
https://github.com/Qowaiv/Qowaiv/blob/77a99cba7f27fc1e92e63d7efc794138f47e7efe/src/Qowaiv/EmailParser.cs#L25

These 3 formats are not supported at the moment:

'"XX Rotterdam <xx@domain.nl>" <xx@domain.nl>'
'"XX \r\n Rotterdam <administratie@domain.nl>" <administratie@domain.nl>'
'"XX Rotterdam <xx@inkoop.exactonline.nl>" <xx@inkoop.exactonline.nl>'

Can you make changes to support them as well?

**Comment by Corniel** [comment]
In other words: email addresses that have a display name in double quotes? I think I can.

**Comment by salmarko** [comment]
Thx :) 👍

**Comment by Corniel** [comment]
I Have a question though: what escaping character is used to escape the double quote?

**Comment by salmarko** [comment]
This is a part of json:

"date":"Mon, 22 Jul 2019 00:52:24 -0700 (PDT)",
"to":[  
"\"Rozey Rotterdam <rotterdam@rozey.nl>\" <rotterdam@rozey.nl>",
"\"Rozey\r\n Rotterdam <administratie@lacubanita.nl>\" <administratie@lacubanita.nl>",
"\"Rozey Rotterdam <k24f@inkoop.exactonline.nl>\" <k24f@inkoop.exactonline.nl>"
],
"messageId":"<5d356b38.1c69fb81.22d9e.bede@mx.google.com>",
"subject":"Factuur 201912885 van 21-07-2019"


So, \

**Comment by Corniel** [comment]
@salmarko Nide some stuff because I think it is data that should not be published out in the open.
