### ISSUE TITLE
Not all email addresses are parsed correctly

### ISSUE THREAD

**Issue by houw0998** [Qowaiv/Qowaiv#75]
Not all email for which we think that they should be accepted can be parsed by qowaiv. Can you improve?
In general those all have the same style containing a text between double quotes and followed by an email between <>
The text between the double quotes seems to go wrong if special characters are used. I see the following generic issue:
a) "XXX Delft <xxx444@inkoop.exactonline.nl>" <xxx444@inkoop.exactonline.nl>
b) "XXX | Delft <xxx444@inkoop.exactonline.nl>" <xxx444@inkoop.exactonline.nl>
c) "XXX ) Delft" <xx4x44@inkoop.exactonline.nl>
d) "XXX Delft ( <xxx444@inkoop.exactonline.nl>" <xxx444@inkoop.exactonline.nl>
e) "XXX, Delft <xxx444@inkoop.exactonline.nl>" <xxx444@inkoop.exactonline.nl>
f) "M. XXX | Delft <xxx444@inkoop.exactonline.nl>" <xxx444@inkoop.exactonline.nl>
g) "<xxx444@inkoop.exactonline.nl>" xxx444@inkoop.exactonline.nl
h) "'<xxx444@inkoop.exactonline.nl>'" <xxx444@inkoop.exactonline.nl>
So the quotes as used in those examples are really single and double quotes 
As you can see I think it goes wrong when either an email address or a special character is used between the double quotes.

[05-09-2019 15:00:19]
I created 8 test cases for this will make it the test ValidEmailAddresses failing. I will reply on the email I got with an txt file.

**Comment by Corniel** [comment]
@houw0998 I could not find that display names are allowed to be decorated using double qoutes. However, I think the support can be added.

**Comment by Corniel** [comment]
@houw0998 I can not reproduce this issue: Which version of Qowaiv are you using?

**Comment by houw0998** [comment]
4.0.2

**Comment by Corniel** [comment]
If I run the following test, it passes:

``` C#
[Test]
public void Parse_WithQuotes_Successful()
{
    var email = EmailAddress.Parse(@"""xxx444@inkoop.exactonline.nl"" xxx444@inkoop.exactonline.nl");
    Assert.AreEqual("xxx444@inkoop.exactonline.nl", email.ToString());
}

So, can you come up with a test that fails?

**Comment by houw0998** [comment]
Please extend the following test in EmailAddressesTest.cs
        public void ValidEmailAddresses(string email)
        {
            Assert.IsTrue(EmailAddress.IsValid(email), email);
        }
with the text cases as provided in the attached file.
You will see that all 8 go wrong.

Regards,
Leo

**Comment by Corniel** [comment]
Well if Iook to what you provided: `"xxx444@inkoop.exactonline.nl<mailto:xxx444@inkoop.exactonline.nl>" xxx444@inkoop.exactonline.nl<mailto:xxx444@inkoop.exactonline.nl>`

I argue this is garbage. Because it has two ways of having a display name combined. Why do you think this should be supported?

**Comment by houw0998** [comment]
So, you say we have to convince our customers not to use those? 
I'm not sure which mail client they come from, but I reproduced one scenario in Outlook.
When I create a new contact in Outlook then i'm able to add every text to the field 'Display as' with or without the email itself. When sending with outlook that field 'Display as' is added as text to the email address. I also love it myself that when I type a name and press <Cntrl>+K that the email shows me the name and the email address so that I'm sure it's the correct one.
My conclusion is that as long as Outlook allows it, its a valid email. I hope you agree

**Comment by Corniel** [comment]
Well the the parser supports all email addresses as described in your issue. The only thing that is does not support is email addresses with the `mailto:`-prefix. That is something that should be supported I suppose. So I'll created an issue for that (#76 ).
